# Generated by Django 5.0.1 on 2024-01-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Models",
            new_name="Character",
        ),
    ]
